name: CI Conditional Change

on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: 'The microservice to deploy'
        required: true
      deployToCH:
        description: 'Deploy to CH region'
        required: true
        default: '0'
      deployToUS:
        description: 'Deploy to US region'
        required: true
        default: '0'
      createDomain:
        description: 'Create domain'
        required: false
        default: '0'

env:
  STAGE: development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - REGION: AWS_CH_REGION
          - REGION: AWS_US_REGION

    steps:
      - name: Should we run?
        run: echo "SHOULD_RUN=`echo ${{ (github.event.inputs.deployToCH == '1' && matrix.REGION == 'AWS_CH_REGION') || (github.event.inputs.deployToUS == '1' && matrix.REGION == 'AWS_US_REGION') }}`" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        if: env.SHOULD_RUN == 'true'

      - name: Set up node
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install packages
        if: env.SHOULD_RUN == 'true'
        run: npm ci

      - name: Creating domain
        if: env.SHOULD_RUN && github.event.inputs.createDomain
        run: echo "create-domain SHOULD_RUN? ${{env.SHOULD_RUN == 'true'}} SHOULD_RUN? ${{env.SHOULD_RUN == '1'}}"

      - name: Deploy package
        if: env.SHOULD_RUN
        run: echo "deploy ${{ github.event.inputs.serviceName }}"
