name: CI Conditional Change

on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: 'The microservice to deploy'
        required: true
      deployToCH:
        description: 'Deploy to CH region'
        required: true
        default: '0'
      deployToUS:
        description: 'Deploy to US region'
        required: true
        default: '0'
      createDomain:
        description: 'Create domain'
        required: false
        default: '0'

env:
  STAGE: development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - REGION: AWS_CH_REGION
          - REGION: AWS_US_REGION

    steps:
      - name: Should we run?
        run: echo "SHOULD_RUN=`${{ (github.event.inputs.deployToCH == '0' && matrix.REGION == 'AWS_CH_REGION') || (github.event.inputs.deployToUS == '0' && matrix.REGION == 'AWS_US_REGION') }}`" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        if: ${{env.SHOULD_RUN == 'true'}}

      - name: Set up node
        if: ${{env.SHOULD_RUN == 1}}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install packages
        if: ${{env.SHOULD_RUN}}
        run: npm ci

      - name: Creating domain
        if: ${{ github.event.inputs.createDomain == '0' }} && ${{env.SHOULD_RUN}}
        run: echo "create-domain ${{env.SHOULD_RUN}} ${{ github.event.inputs.serviceName }} ${{ github.event.inputs.deployToCH }} ${{ github.event.inputs.deployToUS }} ${{ github.event.inputs.createDomain }}"

      - name: Deploy package
        if: ${{env.SHOULD_RUN}}
        run: echo "deploy ${{ github.event.inputs.serviceName }}"
